import { test, expect } from "@playwright/test";
import LoginPage from "../../pages/authPage";
import MainPage from "../../pages/mainPage";
import PaymentPage from "../../pages/paymentPage";
import ThankYouPage from "../../pages/thankYouPage";
import { globalData } from "../../fixtures/global.data";
import { createBUser } from "../../fixtures/billingApi/bUser/bUserCreate/bUserCreateUtils";
import { addMoney } from "../../fixtures/billingApi/bUser/addMoney/addMoneyUtils";
import { getCTVAccountID } from "../../fixtures/billingApi/CTVAccount/createCTVAccountUtils";
import { daysInMonth, periodToPay, remainingDaysInMonth } from "../../fixtures/helpers";
import { servicePrices } from "../../testData/services.data";
import { texts } from "../../testData/texts.data";
import { getCalculateCTVfts } from "../../fixtures/billingApi/bUserPayments/calculateCTV/calculateCTVUtils";
import { formatCurrency } from "../../fixtures/helpers";

test.describe("Pay CTV account", () => {
  let loginPage: LoginPage;
  let mainPage: MainPage;
  let paymentPage: PaymentPage;
  let thankYouPage: ThankYouPage;
  let paymentPageURL: string;
  let userID: number;
  let ctvAccountID: number;

  test.beforeAll(async ({ browser }) => {
    const context = await browser.newContext();
    userID = await createBUser(context.request);
    await await addMoney(context.request, userID, { amount: 10000 });
    ctvAccountID = await getCTVAccountID(context.request, userID);
  });

  test.beforeEach(async ({ page }) => {
    loginPage = new LoginPage(page);
    mainPage = new MainPage(page);
    paymentPage = new PaymentPage(page);
    thankYouPage = new ThankYouPage(page);
    await loginPage.navigateToLoginPage();
    await loginPage.login(String(userID), globalData.defaultPassword);
  });

  test("Cable TV payment", async ({ page, browser }) => {
    test.setTimeout(60000);
    const paymentPage = new PaymentPage(page, ctvAccountID, "ctv");
    const paymentPageURL = paymentPage.pageUrl;
    await page.waitForURL(mainPage.pageUrl);
    // Payment for 1 month
    await mainPage.goToPaymentButton.click();
    await page.waitForURL(paymentPageURL);
    const context = await browser.newContext();
    let fts = await getCalculateCTVfts(context.request, userID, ctvAccountID);
    let currentPeriod = periodToPay(fts);
    let toPayAmount = (servicePrices.ctv / daysInMonth()) * remainingDaysInMonth();
    await expect(paymentPage.pageTitle).toContainText(texts.ua.payment);
    await expect(paymentPage.serviceTitle).toContainText(texts.ua.ctv);
    await expect(paymentPage.serviceAmount).toContainText(`${servicePrices.ctv} ${texts.ua.uahMonth}`);
    await expect(paymentPage.currentPeriod).toContainText(`${currentPeriod}`);
    await paymentPage.spoilerButton.click();
    await expect(paymentPage.checkoutMainField).toContainText(texts.ua.checkout);
    await expect(paymentPage.checkoutMainValue).toContainText(`0.00 грн`);
    await expect(paymentPage.mainServiceField).toContainText(texts.ua.ctv);
    await expect(paymentPage.mainServiceValue).toContainText(`${toPayAmount.toFixed(2)} грн`);
    await expect(paymentPage.cashWithdrawalField).toContainText(texts.ua.cashWithdrawal);
    await expect(paymentPage.cashWithdrawalValue).toContainText(`-${toPayAmount.toFixed(2)} грн`);
    await expect(paymentPage.checkoutField).toContainText(texts.ua.checkout);
    await expect(paymentPage.checkoutValue).toContainText(`0.00 грн`);
    await paymentPage.activateButton.click();
    await page.waitForURL(thankYouPage.successActivatedURL);
    await thankYouPage.toMainButton.click();
    await page.waitForURL(mainPage.pageUrl);
    // Payment for 2 months
    await mainPage.goToPaymentButton.click();
    await page.waitForURL(paymentPageURL);
    fts = await getCalculateCTVfts(context.request, userID, ctvAccountID);
    currentPeriod = periodToPay(fts);
    toPayAmount = servicePrices.ctv * 2;
    await expect(paymentPage.pageTitle).toContainText(texts.ua.payment);
    await expect(paymentPage.serviceTitle).toContainText(texts.ua.ctv);
    await expect(paymentPage.serviceAmount).toContainText(`${servicePrices.ctv} ${texts.ua.uahMonth}`);
    await expect(paymentPage.currentPeriod).toContainText(`${currentPeriod}`);
    await paymentPage.sliderPosition2.click();
    await paymentPage.spoilerButton.click();
    await expect(paymentPage.checkoutMainField).toContainText(texts.ua.checkout);
    await expect(paymentPage.checkoutMainValue).toContainText(`0.00 грн`);
    await expect(paymentPage.mainServiceField).toContainText(texts.ua.ctv);
    await expect(paymentPage.mainServiceValue).toContainText(`${toPayAmount.toFixed(2)} грн`);
    await expect(paymentPage.cashWithdrawalField).toContainText(texts.ua.cashWithdrawal);
    await expect(paymentPage.cashWithdrawalValue).toContainText(`-${toPayAmount.toFixed(2)} грн`);
    await expect(paymentPage.checkoutField).toContainText(texts.ua.checkout);
    await expect(paymentPage.checkoutValue).toContainText(`0.00 грн`);
    await paymentPage.activateButton.click();
    await page.waitForURL(thankYouPage.successActivatedURL);
    await thankYouPage.toMainButton.click();
    await page.waitForURL(mainPage.pageUrl);
    // Payment for 3 months
    await mainPage.goToPaymentButton.click();
    await page.waitForURL(paymentPageURL);
    fts = await getCalculateCTVfts(context.request, userID, ctvAccountID);
    currentPeriod = periodToPay(fts);
    toPayAmount = servicePrices.ctv * 3;
    await expect(paymentPage.pageTitle).toContainText(texts.ua.payment);
    await expect(paymentPage.serviceTitle).toContainText(texts.ua.ctv);
    await expect(paymentPage.serviceAmount).toContainText(`${servicePrices.ctv} ${texts.ua.uahMonth}`);
    await expect(paymentPage.currentPeriod).toContainText(`${currentPeriod}`);
    await paymentPage.sliderPosition3.click();
    await paymentPage.spoilerButton.click();
    await expect(paymentPage.checkoutMainField).toContainText(texts.ua.checkout);
    await expect(paymentPage.checkoutMainValue).toContainText(`0.00 грн`);
    await expect(paymentPage.mainServiceField).toContainText(texts.ua.ctv);
    await expect(paymentPage.mainServiceValue).toContainText(`${toPayAmount.toFixed(2)} грн`);
    await expect(paymentPage.cashWithdrawalField).toContainText(texts.ua.cashWithdrawal);
    await expect(paymentPage.cashWithdrawalValue).toContainText(`-${toPayAmount.toFixed(2)} грн`);
    await expect(paymentPage.checkoutField).toContainText(texts.ua.checkout);
    await expect(paymentPage.checkoutValue).toContainText(`0.00 грн`);
    await paymentPage.activateButton.click();
    await page.waitForURL(thankYouPage.successActivatedURL);
    await thankYouPage.toMainButton.click();
    await page.waitForURL(mainPage.pageUrl);
    // Payment for 5 months
    await mainPage.goToPaymentButton.click();
    await page.waitForURL(paymentPageURL);
    fts = await getCalculateCTVfts(context.request, userID, ctvAccountID);
    currentPeriod = periodToPay(fts);
    toPayAmount = servicePrices.ctv * 5;
    await expect(paymentPage.pageTitle).toContainText(texts.ua.payment);
    await expect(paymentPage.serviceTitle).toContainText(texts.ua.ctv);
    await expect(paymentPage.serviceAmount).toContainText(`${servicePrices.ctv} ${texts.ua.uahMonth}`);
    await expect(paymentPage.currentPeriod).toContainText(`${currentPeriod}`);
    await paymentPage.sliderPosition5.click();
    await paymentPage.spoilerButton.click();
    await expect(paymentPage.checkoutMainField).toContainText(texts.ua.checkout);
    await expect(paymentPage.checkoutMainValue).toContainText(`0.00 грн`);
    await expect(paymentPage.mainServiceField).toContainText(texts.ua.ctv);
    await expect(paymentPage.mainServiceValue).toContainText(`${toPayAmount.toFixed(2)} грн`);
    await expect(paymentPage.cashWithdrawalField).toContainText(texts.ua.cashWithdrawal);
    await expect(paymentPage.cashWithdrawalValue).toContainText(`-${toPayAmount.toFixed(2)} грн`);
    await expect(paymentPage.checkoutField).toContainText(texts.ua.checkout);
    await expect(paymentPage.checkoutValue).toContainText(`0.00 грн`);
    await paymentPage.activateButton.click();
    await page.waitForURL(thankYouPage.successActivatedURL);
    await thankYouPage.toMainButton.click();
    await page.waitForURL(mainPage.pageUrl);
    // Payment for 6 months
    await mainPage.goToPaymentButton.click();
    await page.waitForURL(paymentPageURL);
    fts = await getCalculateCTVfts(context.request, userID, ctvAccountID);
    currentPeriod = periodToPay(fts);
    toPayAmount = servicePrices.ctv * 6;
    await expect(paymentPage.pageTitle).toContainText(texts.ua.payment);
    await expect(paymentPage.serviceTitle).toContainText(texts.ua.ctv);
    await expect(paymentPage.serviceAmount).toContainText(`${servicePrices.ctv} ${texts.ua.uahMonth}`);
    await expect(paymentPage.currentPeriod).toContainText(`${currentPeriod}`);
    await paymentPage.sliderPosition6.click();
    await paymentPage.spoilerButton.click();
    await expect(paymentPage.checkoutMainField).toContainText(texts.ua.checkout);
    await expect(paymentPage.checkoutMainValue).toContainText(`0.00 грн`);
    await expect(paymentPage.mainServiceField).toContainText(texts.ua.ctv);
    await expect(paymentPage.mainServiceValue).toContainText(`${toPayAmount.toFixed(2)} грн`);
    await expect(paymentPage.cashWithdrawalField).toContainText(texts.ua.cashWithdrawal);
    await expect(paymentPage.cashWithdrawalValue).toContainText(`-${toPayAmount.toFixed(2)} грн`);
    await expect(paymentPage.checkoutField).toContainText(texts.ua.checkout);
    await expect(paymentPage.checkoutValue).toContainText(`0.00 грн`);
    await paymentPage.activateButton.click();
    await page.waitForURL(thankYouPage.successActivatedURL);
    await thankYouPage.toMainButton.click();
    await page.waitForURL(mainPage.pageUrl);
    // Payment for 11 months
    await mainPage.goToPaymentButton.click();
    await page.waitForURL(paymentPageURL);
    fts = await getCalculateCTVfts(context.request, userID, ctvAccountID);
    currentPeriod = periodToPay(fts);
    toPayAmount = servicePrices.ctv * 11;
    await expect(paymentPage.pageTitle).toContainText(texts.ua.payment);
    await expect(paymentPage.serviceTitle).toContainText(texts.ua.ctv);
    await expect(paymentPage.serviceAmount).toContainText(`${servicePrices.ctv} ${texts.ua.uahMonth}`);
    await expect(paymentPage.currentPeriod).toContainText(`${currentPeriod}`);
    await paymentPage.sliderPosition11.click();
    await paymentPage.spoilerButton.click();
    await expect(paymentPage.checkoutMainField).toContainText(texts.ua.checkout);
    await expect(paymentPage.checkoutMainValue).toContainText(`0.00 грн`);
    await expect(paymentPage.mainServiceField).toContainText(texts.ua.ctv);
    await expect(paymentPage.mainServiceValue).toContainText(`${formatCurrency(toPayAmount)} грн`);
    await expect(paymentPage.cashWithdrawalField).toContainText(texts.ua.cashWithdrawal);
    await expect(paymentPage.cashWithdrawalValue).toContainText(`-${formatCurrency(toPayAmount)} грн`);
    await expect(paymentPage.checkoutField).toContainText(texts.ua.checkout);
    await expect(paymentPage.checkoutValue).toContainText(`0.00 грн`);
    await paymentPage.activateButton.click();
    await page.waitForURL(thankYouPage.successActivatedURL);
    await thankYouPage.toMainButton.click();
    await page.waitForURL(mainPage.pageUrl);
    // Payment for 12 months
    await mainPage.goToPaymentButton.click();
    await page.waitForURL(paymentPageURL);
    fts = await getCalculateCTVfts(context.request, userID, ctvAccountID);
    currentPeriod = periodToPay(fts);
    toPayAmount = servicePrices.ctv * 12;
    await expect(paymentPage.pageTitle).toContainText(texts.ua.payment);
    await expect(paymentPage.serviceTitle).toContainText(texts.ua.ctv);
    await expect(paymentPage.serviceAmount).toContainText(`${servicePrices.ctv} ${texts.ua.uahMonth}`);
    await expect(paymentPage.currentPeriod).toContainText(`${currentPeriod}`);
    await paymentPage.sliderPosition12.click();
    await paymentPage.spoilerButton.click();
    await expect(paymentPage.checkoutMainField).toContainText(texts.ua.checkout);
    await expect(paymentPage.checkoutMainValue).toContainText(`0.00 грн`);
    await expect(paymentPage.mainServiceField).toContainText(texts.ua.ctv);
    await expect(paymentPage.mainServiceValue).toContainText(`${formatCurrency(toPayAmount)} грн`);
    await expect(paymentPage.cashWithdrawalField).toContainText(texts.ua.cashWithdrawal);
    await expect(paymentPage.cashWithdrawalValue).toContainText(`-${formatCurrency(toPayAmount)} грн`);
    await expect(paymentPage.checkoutField).toContainText(texts.ua.checkout);
    await expect(paymentPage.checkoutValue).toContainText(`0.00 грн`);
    await paymentPage.activateButton.click();
    await page.waitForURL(thankYouPage.successActivatedURL);
    await thankYouPage.toMainButton.click();
    await page.waitForURL(mainPage.pageUrl);
  });
});
